### ISSUE TITLE
@Nested - ClassCastException

### ISSUE THREAD

**Issue by GuyJackson** [origin-energy/java-snapshot-testing#42]
Just attempting to migrate to `2.0.0` from `2.0.0-Beta6`. After running my test class again they are all ignored.

The exception I'm getting is:

```
java.lang.ClassCastException: class org.junit.jupiter.engine.descriptor.NestedClassTestDescriptor cannot be cast to class org.junit.jupiter.engine.descriptor.ClassTestDescriptor (org.junit.jupiter.engine.descriptor.NestedClassTestDescriptor and org.junit.jupiter.engine.descriptor.ClassTestDescriptor are in unnamed module of loader 'app')

	at au.com.origin.snapshots.junit5.SnapshotExtension.shouldFailOnOrphans(SnapshotExtension.java:54)
	at au.com.origin.snapshots.junit5.SnapshotExtension.beforeAll(SnapshotExtension.java:21)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$7(ClassBasedTestDescriptor.java:359)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:359)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:189)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

I'm using `@Nested` classes and have a structure like this:

```
@SpringBootTest(webEnvironment = RANDOM_PORT)
@ExtendWith({SnapshotExtension.class})
public class AssessmentCaptureApiTest {


  @Nested
  class Given_something {

    @Test
    public void when_example_then_something_updated() {

      //body

      SnapshotMatcher.expect(someTestObject).toMatchSnapshot();
    }
  }
}
```

Any help appreciated. 

The only reason I'm migrating to `2.0.0` now is that I want to ignore a certain field in the snapshot - would appreciate if you could advise on a workaround for this for Beta6?

I've also noticed when using `@Nested` that an empty snap file gets generated for the annotated class.

Finally - thank you for the work on this project - I think this is a fantastic extension which I have been looking for a while (having used jest). I'll be happy to help features/documentation in the future should there be a requirement.

Guy

**Comment by jackmatt2** [comment]
Yeah so this will be related to 

https://github.com/origin-energy/java-snapshot-testing/blob/master/java-snapshot-testing-junit5/src/main/java/au/com/origin/snapshots/junit5/SnapshotExtension.java#L45-L65

Appears using `@Nested` is breaks the orphan check.

**Comment by jackmatt2** [comment]
A workaround for now is to do this and use @Extends(MySnapshotExtension.class)

```
public class MySnapshotExtension extends SnapshotExtension {

    @Override
    public void beforeAll(ExtensionContext context) {
        Class<?> testClass = context.getTestClass()
                .orElseThrow(() -> new SnapshotMatchException("Unable to locate Test class"));
        SnapshotMatcher.start(getSnapshotConfig(), false, testClass);
    }

}
```

**Comment by jackmatt2** [comment]
@GuyJackson I just wrote a test for this and it in fact worked.  Can you give me your JUnit5 version?

**Comment by jackmatt2** [comment]
I'm catching ClassCastException so at lest it will just warn now instead of blowing up in the latest snapshot `2.1.0`. Can you check if your JUnit is >= 5.3.2?

**Comment by GuyJackson** [comment]
Thanks @jackmatt2 so junit-jupiter version is `<junit-jupiter.version>5.6.3</junit-jupiter.version>` which specified in parent pom for springboot via the junit-bom:

```
<dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>${junit-jupiter.version}</version>
        <type>pom</type>
        <scope>import</scope>
</dependency>
```
Can you let me know what version you tested against please and I can try?

**Comment by GuyJackson** [comment]
Hi @jackmatt2 - so I've created a new spring boot project - with a new test class:

```
package com.example.demo;

import au.com.origin.snapshots.SnapshotMatcher;
import au.com.origin.snapshots.junit5.SnapshotExtension;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
@ExtendWith({SnapshotExtension.class})
class DemoApplicationTests {

  @Test
  void snapshot_test_class_level() {

    SnapshotMatcher.expect("something").toMatchSnapshot();

  }

  @Nested
  class NestedClass {

    @Test
    void snapshot_test_nested() {

      SnapshotMatcher.expect("something").toMatchSnapshot();
    }
  }
}
```

The first test passes and the second (`@Nested`) one is ignored with the aforementioned error.

`mvn dependency:tree` for the `spring-boot-starter-test`:

> [INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.3.5.RELEASE:test
> [INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.3.5.RELEASE:test
> [INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.3.5.RELEASE:test
> [INFO] |  +- com.jayway.jsonpath:json-path:jar:2.4.0:test
> [INFO] |  |  +- net.minidev:json-smart:jar:2.3:test
> [INFO] |  |  |  \- net.minidev:accessors-smart:jar:1.2:test
> [INFO] |  |  |     \- org.ow2.asm:asm:jar:5.0.4:test
> [INFO] |  |  \- org.slf4j:slf4j-api:jar:1.7.30:compile
> [INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:test
> [INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:test
> [INFO] |  +- org.assertj:assertj-core:jar:3.16.1:test
> [INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
> [INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.6.3:test
> [INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.6.3:test
> [INFO] |  |  |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
> [INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
> [INFO] |  |  |  \- org.junit.platform:junit-platform-commons:jar:1.6.3:test
> [INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.6.3:test
> [INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.6.3:test
> [INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.6.3:test
> [INFO] |  +- org.mockito:mockito-core:jar:3.3.3:test
> [INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.10.17:test
> [INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.17:test
> [INFO] |  |  \- org.objenesis:objenesis:jar:2.6:test
> [INFO] |  +- org.mockito:mockito-junit-jupiter:jar:3.3.3:test
> [INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
> [INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
> [INFO] |  +- org.springframework:spring-test:jar:5.2.10.RELEASE:test
> [INFO] |  \- org.xmlunit:xmlunit-core:jar:2.7.0:test
> [INFO] +- io.github.origin-energy:java-snapshot-testing-junit5:jar:2.0.0:compile

**Comment by jackmatt2** [comment]
Only the SNAPSHOT is updated currently

`io.github.origin-energy:java-snapshot-testing-junit5:jar:2.1.0-SNAPSHOT`

I have docs in the README on how to use SNAPSHOTS in gradle.
